version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: . # location
      args: # ARGS in docker file 
        NODE_ENV: development
    volumes:
      - ./:/app # bind mount
      - /app/node_modules # anonymous volume
    environment:
      - NODE_ENV=development  
      - MONGO_USER=donald
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev  

  mongo: # otherwise we use the command key
    environment:
      - MONGO_INITDB_ROOT_USERNAME=donald
      - MONGO_INITDB_ROOT_PASSWORD=mypassword 
