version: '3'
services: 
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app: # when building our own image we use build
    build: .
    image: cameroondocker/node-docker-app
    # ports:  # nginx takes car of this now
    #   - "3000-3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo  

  mongo: # otherwise we use the command key
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=donald
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  redis: # otherwise we use the command key
    image: redis


volumes:
  mongo-db: